version: "3.8"

services:
  web:
    build: .
    container_name: "${PROJECT}-web"
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
      - redis
    restart: always
    environment:
      - VIRTUAL_HOST=${DOMAINS}
      - LETSENCRYPT_HOST=${SSL_DOMAINS}
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: mysql:8.0
    container_name: "${PROJECT}-db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: development
      MYSQL_USER: development
      MYSQL_PASSWORD: development
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT}-phpmyadmin"
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - VIRTUAL_HOST=${SQL_DOMAINS}
      - LETSENCRYPT_HOST=${SQL_SSL_DOMAINS}

  redis:
    image: redis:latest
    container_name: "${PROJECT}-redis"
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
